// <auto-generated />
using IIASA.EOCS.PhotoMicroService.DBContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace IIASA.EOCS.PhotoMicroService.Migrations
{
    [DbContext(typeof(PhotoContext))]
    [Migration("20190323153342_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("IIASA.EOCS.PhotoMicroService.Models.DirectionType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("DirectionTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Photo Taken towards North",
                            Name = "North"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Photo Taken towards South",
                            Name = "South"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Photo Taken towards East",
                            Name = "East"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Photo Taken towards West",
                            Name = "West"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Photo Taken towards Ground",
                            Name = "Ground"
                        });
                });

            modelBuilder.Entity("IIASA.EOCS.PhotoMicroService.Models.LandCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("LandCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Land with house and Aprtments",
                            Name = "Residential"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Cinema, Museums,Airport etc...",
                            Name = "Amenities"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Parks, Stadiumms etc..",
                            Name = "Recreation,Sport"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Shops, Supermarkets etc...",
                            Name = "Commerce"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Building or developement going on.",
                            Name = "Construction"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Crops or other fileds.",
                            Name = "Agriculture"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Forest land.",
                            Name = "Forestry"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Factory or Manufacturing Plants.",
                            Name = "Insdustry"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Road, streets or Rail.",
                            Name = "Transport"
                        });
                });

            modelBuilder.Entity("IIASA.EOCS.PhotoMicroService.Models.Photo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description");

                    b.Property<string>("FilePath");

                    b.Property<string>("DeviceName");

                    b.Property<int>("DirectionTypeId");

                    b.Property<int>("LandCategoryId");

                    b.Property<string>("FileName");

                    b.HasKey("Id");

                    b.ToTable("Photos");
                });
#pragma warning restore 612, 618
        }
    }
}
